### ISSUE TITLE
Error in import in Firefox: Error: Cannot import "toSource": already exists

### ISSUE THREAD

**Issue by man-shar** [josdejong/mathjs-expression-parser#2]
I am getting this particular error in Firefox which leads to my bundle crashing with an error. But it works fine on Chrome.

Error: Cannot import "toSource": already exists.

Is this a webpack error or some other problem with the way I have imported the library? Is there any way I can fix this? My project is uploaded [here](https://github.com/manas271196/btp-react/blob/master/)

The import line that is causing the error is [here](https://github.com/manas271196/btp-react/blob/master/src/Util/ShapeUtil.js#L1)

**Comment by dim2k2006** [comment]
I have the same issue in firefox! Any ideas how to fix it?

**Comment by man-shar** [comment]
Yeah a fix is in this PR. But it has been open for a while now.: 
https://github.com/josdejong/mathjs-expression-parser/pull/1

**Comment by dim2k2006** [comment]
@manas271196 Thanks for quick response! But I have already use another library https://github.com/silentmatt/expr-eval . Thank goodness my project has tests so the replacement went seamlessly!)

**Comment by josdejong** [comment]
(Finally) fixed now in `v1.0.1`, see #1
